name: coverage
on:
  - push
  - pull_request
jobs:
  coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ArtiomTr/jest-coverage-report-action@v2
        with:
          package-manager: yarn
